export enum NamesService {
  COMMUNICATION = 'COMMUNICATION',
  ANALYTIC = 'ANALYTIC',
  USER = 'USER',
  INTEREST = 'INTEREST',
}

export enum EmitPattern {
  userCreated = 'TCP::USER//USER_CREATED',
  //USERS
  CREATE_USER = 'TCP::USER//CREATE_USER',
  GET_USER_BY_ID = 'TCP::USER//GET_USER_BY_ID',
  GET_ALL_USERS = 'TCP::USER/GET_ALL_USERS',
  GET_PAGINATED_USERS = 'TCP::USER//GET_PAGINATED_USERS',
  UPDATE_USER = 'TCP::USER//UPDATE_USER',
  SOFT_DELETE_USER = 'TCP::USER//SOFT_DELETE_USER',
  HARD_DELETE_USER = 'TCP::USER//HARD_DELETE_USER',
  //CATEGORY
  CREATE_CATEGORY = 'TCP::CATEGORY//CREATE_CATEGORY',
  GET_CATEGORY_BY_ID = 'TCP::CATEGORY//GET_CATEGORY_BY_ID',
  GET_ALL_CATEGORIES = 'TCP::CATEGORY/GET_ALL_CATEGORIES',
  GET_PAGINATED_CATEGORIES = 'TCP::CATEGORY//GET_PAGINATED_CATEGORIES',
  UPDATE_CATEGORY = 'TCP::CATEGORY//UPDATE_CATEGORY',
  SOFT_DELETE_UCATEGORY = 'TCP::UCATEGORY//SOFT_DELETE_UCATEGORY',
  HARD_DELETE_CATEGORY = 'TCP::CATEGORY//HARD_DELETE_CATEGORY',
  // PROFESSION
  CREATE_PROFESSION = 'TCP::PROFESSION//CREATE_PROFESSION',
  GET_PROFESSION_BY_ID = 'TCP::PROFESSION//GET_PROFESSION_BY_ID',
  GET_ALL_PROFESSIONS = 'TCP::PROFESSION/GET_ALL_PROFESSIONS',
  GET_PAGINATED_PROFESSION = 'TCP::PROFESSION//GET_PAGINATED_PROFESSION',
  UPDATE_PROFESSION = 'TCP::PROFESSION//UPDATE_PROFESSION',
  SOFT_DELETE_PROFESSION = 'TCP::PROFESSION//SOFT_DELETE_PROFESSION',
  HARD_DELETE_PROFESSION = 'TCP::PROFESSION//HARD_DELETE_PROFESSION',
  //OTHER
}


export enum SendCmdPattern {
  getAnalytics = 'TCP::ANALYTC/GET_ANALYTICS',
}
