export const USER_SERVER_MESSAGE = {
    CREATED_SUCCESS: 'USER::CREATE//USER CREATED SUCCESSFULLY',
    CREATED_ERROR: 'USER::CREATE:://USER DID NOT CREATED, SOMETHING WENT WRONG',
    // UPDATED_ERROR: 'USER::UPDATED:://USER DID NOT UPDATED, SOMETHING WENT WRONG',
    // UPDATED_SUCCESS: 'USER::UPDATE:://USER UPDATED SUCCESSFULLY',
    GET_ITEM_BY_ID: 'USER::GET:://GET USER BY ID',
    GET_ALL_ITEMS_SUCCES: 'USER::GET:://GET ALL USERS SUCCESSFULLY',
    GET_ALL_ITEMS_ERROR: 'USER::GET:://GET ALL USERS RETURN ERROR | SOMETHING WENT WRONG',
    // GET_PAGINATED_ITEMS: 'USER::GET:://GET PAGINATED USERS',
    // GET_PAGINATED_ITEMS_BY_DATE: 'USER::GET:://GET PAGINATED USERS BY DATE',
    // GET_ITEMS_BY_DATE: 'USER::GET:://GET USERS BY DATE',
    // GET_PAGINATED_ITEMS_BY_DATE_BY_ENTITY: 'USER::GET:://GET PAGINATED USERS BY DATE BY ENTITY',
    // GET_ITEMS_BY_DATE_BY_ENTITY: 'USER::GET:://GET USERS BY DATE BY ENTITY',
    // GET_PAGINATED_ITEMS_BY_DATE_BY_USER: 'USER::GET:://GET PAGINATED USERS BY DATE BY USER',
    // GET_ITEMS_BY_DATE_BY_USER: 'USER::GET:://GET USERS BY DATE BY USER',
    // GET_LAST_ITEM_BY_USER: 'USER::GET:://GET LAST USER BY USER',
    DELETE_SUCCESS: 'USER::DELETE:://USER DELETED SUCCESSFULLY',
    // DELETE_ERROR: 'USER::DELETE:://USER DID NOT DELETED, SOMETHING WENT WRONG',

    UPDATE_SUCCESS: 'USER::CREATE//USER UPDATE SUCCESSFULLY',
    UPDATE_ERROR: 'USER::CREATE:://USER DID NOT UPDATE, SOMETHING WENT WRONG',
}

